### ISSUE TITLE
PSCustomObject support

### ISSUE THREAD

**Issue by johnduprey** [PalmEmanuel/AzBobbyTables#12]
It would be beneficial for the module to support PSCustomObjects in addition to hashtables for a more native PowerShell experience.

**Comment by PalmEmanuel** [comment]
Good idea, I'll see if there's a neat way to implement a -OutputFormat parameter or similar.

**Comment by PalmEmanuel** [comment]
Note to self: Might be able to change the `-Entity` parameter type to `object[]` and validate against Hashtable or PSObject to avoid needing to specify which format is needed. This also means that the user's input data type could be saved to determine the output format if needed.
