### ISSUE TITLE
Support odata filters that are longer than allowed

### ISSUE THREAD

**Issue by kevinblumenfeld** [PalmEmanuel/AzBobbyTables#18]

**Comment by kevinblumenfeld** [comment]
Perhaps this isn’t possible but I ran into this recently.

**Comment by kevinblumenfeld** [comment]
I need to properly research prior to opening this issue in future. Apologies.

**Comment by PalmEmanuel** [comment]
Let me know if you encounter any specific problems that are easy to recreate, in that case I can also take a look at it and see if there are some workarounds @kevinblumenfeld 👍
