### ISSUE TITLE
When adding a hashtable to table, Null values throw the error `Object reference not set to an instance of an object.`

### ISSUE THREAD

**Issue by kevinblumenfeld** [PalmEmanuel/AzBobbyTables#19]
Apologies if I am missing a way for me to handle this error.

When i add an array of hashtables with Add-AzDataTableEntity and any of the values of the key-value pairs are null, it fails with `Object reference not set to an instance of an object.`

I am using a null coalesce operator `??` but it seems to slow down the process:

![image](https://user-images.githubusercontent.com/28877715/206948983-4cca21e8-b75b-4b20-a99d-881429e8e6b6.png)

Thank you!

**Comment by PalmEmanuel** [comment]
Thanks for reporting it! I'll make sure we handle this better in the module.
