### ISSUE TITLE
DateTimeOffsets don't maintain timezone info

### ISSUE THREAD

**Issue by Szeraax** [PalmEmanuel/AzBobbyTables#42]
## Observed Behavior
When adding an entity, if a property is a dto, it will be converted to zulu (UTC/Z/+00:00) prior to adding to the table. 

## Expected Behavior
dtos maintain tz info,

## Steps to reproduce

```
PS C:\> $dto = (get-Date) -as [System.DateTimeOffset]
PS C:\> $dto

DateTime      : 12/25/2023 4:33:31 PM
UtcDateTime   : 12/25/2023 11:33:31 PM
LocalDateTime : 12/25/2023 4:33:31 PM
Date          : 12/25/2023 12:00:00 AM
Day           : 25
DayOfWeek     : Monday
DayOfYear     : 359
Hour          : 16
Millisecond   : 119
Minute        : 33
Month         : 12
Offset        : -07:00:00
Second        : 31
Ticks         : 638391188111190092
UtcTicks      : 638391440111190092
TimeOfDay     : 16:33:31.1190092
Year          : 2023


PS C:\> $dto.ToString('o')
2023-12-25T16:33:31.1190092-07:00
PS C:\> Add-AzDataTableEntity -Context $ctx -Entity @{PartitionKey='';RowKey='';Time = $dto} 
PS C:\> Get-AzDataTableEntity -Context $ctx

ETag         : W/"datetime'2023-12-25T23%3A33%3A48.3098466Z'"
PartitionKey :
RowKey       :
Time         : 12/25/2023 11:33:31 PM +00:00
Timestamp    : 12/25/2023 11:33:48 PM +00:00


PS C:\> # Table view: 2023-12-25T23:33:31.1190092Z
PS C:\>
```

If I manually set the datetime field in Az via storage explorer to the `$dto.ToString('o')` value (`2023-12-25T16:33:31.1190092-07:00`), then getting the entity works like expected:

```
PS C:\> Get-AzDataTableEntity -Context $a

ETag         : W/"datetime'2023-12-25T23%3A37%3A15.3929259Z'"
PartitionKey :
RowKey       :
Time         : 12/25/2023 4:33:31 PM -07:00
Timestamp    : 12/25/2023 11:37:15 PM +00:00

PS C:\> # Table view: 2023-12-25T16:33:31.1190092-07:00
```

It is entirely possible that this is a limitation of the SDK that you use since you reference the SupportedTypesList with dto and I don't see any custom dto logic. 

I'm unsure of any way to store a dto with its tz info preserved at current with AzBobbyTables.

**Comment by Szeraax** [comment]
Ah ha. https://github.com/Azure/azure-sdk-for-net/issues/30644

**Comment by Szeraax** [comment]
Based on the conversations there, it seems like it is entirely an SDK issue and not an AzBobbyTables issue, so I'm going to go ahead and close.

**Comment by PalmEmanuel** [comment]
This seems like something to document in the module with an example of what to avoid, thanks!
