### ISSUE TITLE
Feature Request: Add CreateIfNotExistsAsync() support from TableClient

### ISSUE THREAD

**Issue by johnduprey** [PalmEmanuel/AzBobbyTables#5]
This would allow us to retrieve a table or create it if it does not exist. 
https://docs.microsoft.com/en-us/azure/cosmos-db/table/create-table-dotnet?tabs=azure-cli%2Cwindows#create-a-table

**Comment by PalmEmanuel** [comment]
Great suggestion, I'll implement it as soon as possible!
