### ISSUE TITLE
Does ManagedIdentity switch only supports system assigned identity?

### ISSUE THREAD

**Issue by gummigroda** [PalmEmanuel/AzBobbyTables#51]
Hi and thanks for creating this module!

Trying it out locally with tokens and it works as I expect. 
When trying it an Azure function app, I get an `The remote server returned an error: (400) Bad Request. ` 
The function app is not using a system assigned identity, but instead a user managed identity.

Not being a dev, to me this line looks like it assumes the function has an system assigned identity?
https://github.com/PalmEmanuel/AzBobbyTables/blob/8dfd139660808bbf10b93d84fc1c343a8c4e9b06/source/AzBobbyTables.Core/Helpers.cs#L15

Would it be possible to add support for `umi`, supplying the client_id as parameter to the URI?

https://learn.microsoft.com/en-us/azure/app-service/overview-managed-identity?toc=%2Fazure%2Fazure-functions%2Ftoc.json&tabs=portal%2Cpowershell#rest-endpoint-reference

Or am I just doing it wrong?

**Comment by PalmEmanuel** [comment]
Great catch, absolutely! I think you're right, and it's just something that I missed since I usually run it with system-assigned managed identities.

I'll add it to the list and make sure to fix that 👍

**Comment by PalmEmanuel** [comment]
Version 3.1.3 is now out with support for UAMIs, would be happy to hear if it solved your issue @gummigroda :)

**Comment by gummigroda** [comment]
Glimmrande, works super. 
Thanks for the quick update!
