### ISSUE TITLE
E-Tag Validation for DeleteEntity UpdateEntity (Merge) UpdateEntity (Replace)

### ISSUE THREAD

**Issue by Studermarc** [PalmEmanuel/AzBobbyTables#58]
The TableTransactionTypes "Delete", "UpdateMerge", and "UpdateReplace" support the ETag validation based on the Library Documentation: [https://learn.microsoft.com/en-us/dotnet/api/azure.data.tables.tabletransactionactiontype?view=azure-dotnet](https://learn.microsoft.com/en-us/dotnet/api/azure.data.tables.tabletransactionactiontype?view=azure-dotnet)

Would it be possible to add this functionality to the Cmdlets "Remove-AzDataTableEntity" and "Update-AzDataTableEntity"

I have many scenarios, where I need to Update or Delete an Entity only if it hasn't changed between the time of retrieval of the Entity (which also provides the Etag) and the Delete or Update Operation.

Let me know if more Context is needed, I'm happy to provide more Inputs.

**Comment by PalmEmanuel** [comment]
That sounds like a useful feature for sure, I'll have a look.

I would consider this to be the new default behavior, with a -Force option to overwrite regardless. Would you agree this is an expected user experience?

**Comment by Studermarc** [comment]
Absolutely. This makes the most sense and it aligns with the rest API behaviour, where you have to pass the ifmatch header with * as value if you want the operation to execute unconditionally.

**Comment by Studermarc** [comment]
Hi, do you need some help with testing? I'd love to use your module in my next project. I do need the etag functionality for it though. Kind regards, Marc

**Comment by PalmEmanuel** [comment]
I tested the functionality manually and released a new version of the module, let me know if something isn't working @Studermarc!

**Comment by Studermarc** [comment]
A bit late, but many Thanks for the development. I finally had the chance to put it to use in our project. it works nicely.

**Comment by PalmEmanuel** [comment]
Happy to hear that 👍
