### ISSUE TITLE
Add a "Replace" Switch to the Update-AzDataTableEntity

### ISSUE THREAD

**Issue by Studermarc** [PalmEmanuel/AzBobbyTables#59]
Per default, the default behaviour of the Update-AzDataTableEntity is to Merge the Entity Properties. Adding a -Replace Switch would provide more flexibility to the User to chose how the Entities are Updated.

Happy to provide more Inputs if needed. Kind regards.

**Comment by Studermarc** [comment]
Wow this is awesome. Many thanks! Your module is great. I use it in all my projects involving storage tables. 
Is the default the same as before? Or must the operation type be specified?

**Comment by PalmEmanuel** [comment]
The default is still the same! I wanted to ensure no breaking changes.

Might change the parameter setup in a major breaking version later in the future, but for now you can both use -Force or -OperationType UpsertReplace for the same result in Add-AzDataTableEntity for example 👍
