### ISSUE TITLE
Add a "-Merge" -Switch to the Add-AzDataTableEntity Cmdlet

### ISSUE THREAD

**Issue by Studermarc** [PalmEmanuel/AzBobbyTables#60]
The current implementation of the  Add-AzDataTableEntity  allows the use of the -Force Switch to Force the addition of the Entity to the DataTable, if already existing, with the UpsertReplace Method, which Replaces the Existing Entity. 

Providing a -Merge Switch would allow more flexibility in the behaviour those Entities are added.

Alternatively, instead of the -Force Switch, two switches could be implemented to provide more clarity for the users in regards to the behaviour:
a -Merge Switch to Merge the new Entity with the existing one and
a -Replace Switch to Replace the existing Entity with the new one.

Happy to provide more context if needed. Kind regards.

**Comment by PalmEmanuel** [comment]
Thanks for the issue! I'll have a look at this together with #59

**Comment by Studermarc** [comment]
Many thanks. Let me know if you want to discuss the different options, default behaviour, etc. I'm happy to hop in a quick teams call for this.

**Comment by PalmEmanuel** [comment]
Hey @Studermarc! Apologies that it took a while to implement it, but there's now an `-OperationType` parameter which allows for changing the operation/transaction logic on both `Add-AzDataTableEntity` (Add/UpsertMerge/UpsertReplace) and `Update-AzDataTableEntity` (UpdateReplace/UpdateMerge) 🙂 

Available in [v3.3.1](https://www.powershellgallery.com/packages/AzBobbyTables/3.3.1) now.
