### ISSUE TITLE
Add Get-AzDataTable cmdlet

### ISSUE THREAD

**Issue by JohnDuprey** [PalmEmanuel/AzBobbyTables#77]
It looks like you can query a table listing using TableServiceClient.Query to get all the tables in a storage account. This could be extremely useful when cleaning up storage accounts.  

https://learn.microsoft.com/en-us/dotnet/api/azure.data.tables.tableserviceclient.query?view=azure-dotnet

**Comment by PalmEmanuel** [comment]
Great suggestion, sounds like a good use case!
