### ISSUE TITLE
Evaluate performance improvements by allowing selection of only specific columns

### ISSUE THREAD

**Issue by PalmEmanuel** [PalmEmanuel/AzBobbyTables#8]
Is it worth implementing a parameter to select only specific columns from table entries? Compare performance to `| Select-Object`.

**Comment by PalmEmanuel** [comment]
> Just thought of another thing to add, select support to return specific columns, could bring additional speed boosts (e.g. returning just PartitionKey)

**Comment by johnduprey** [comment]
@PalmEmanuel have you considered this feature any further? We're now seeing issues when table rows get to the thousands and cross partition keys. The use case here is to return a unique list of partition keys to limit the rows returned in the actual query.

**Comment by PalmEmanuel** [comment]
@johnduprey this is now live in version 2.2.2, hope it helps! 😃
