### ISSUE TITLE
Explore possibility to clear table using a more efficient way

### ISSUE THREAD

**Issue by PalmEmanuel** [PalmEmanuel/AzBobbyTables#9]
Currently, to clear a table, one has to get all entities and then remove all entities. Is it possible to clear a table in another way and build a new command around that?

**Comment by johnduprey** [comment]
Using the new select column support you can limit what is returned down to PartitionKey and RowKey, this should speed up a full table clear significantly. Alternatively you could just delete the whole table and let it recreate.

**Comment by PalmEmanuel** [comment]
Absolutely, I think that's the way I will build it but with a new command so it doesn't have to pass all the hashtable conversions.
